version: '3'

services:

  vc-db:
    image: kkbruce/mssql-server-windows-express:windowsservercore-1809
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=v!rto_Labs!
    networks:
      - virto

  vc-platform-web:
    image: platform-core:dev
    ports:
      - "${DOCKER_PLATFORM_PORT:-8090}:80"
    environment:
      - ConnectionStrings:VirtoCommerce=Data Source=vc-db;Initial Catalog=VirtoCommerce2;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=True;Connect Timeout=30;
      - Assets:Provider=FileSystem
      - Assets:FileSystem:RootPath=~/App_Data/Assets
      - Assets:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/assets
    depends_on:
      - vc-db
    volumes:
      - cms-content-volume:c:\vc-platform\App_Data\cms-content
    networks:
      - virto

  vc-storefront-web:
    image: virtocommerce/storefront:${DOCKER_TAG:-latest}
    ports:
      - "${DOCKER_STOREFRONT_PORT:-8090}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT:Development
      - VirtoCommerce:Endpoint:Url=http://vc-platform-web
      - ConnectionStrings:ContentConnectionString=provider=LocalStorage;rootPath=~/cms-content
    depends_on:
      - vc-platform-web
    volumes:
      - cms-content-volume:C:\vc-storefront\wwwroot\cms-content
    networks:
      - virto

volumes:
  cms-content-volume:

networks:
  virto:
    driver: nat